config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  resources :admins
  resources :users
  resources :sources do
    collection do
      get 'search'
    end
  end
  root to: 'sources#index'
end

app/models/source.rb
class Source < ApplicationRecord
  belongs_to :admin
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :grade

  with_options presence: true do
    validates :title
    validates :category_id
    validates :grade_id
    validates :content
  end

  # def self.search(search)
  #   if search != ""
  #     Source.where('content LIKE(?)', "%#{search}%")
  #   else
  #     Source.all
  #   end
  # end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search]
  before_action :search_source, only: [:index, :search]
  before_action :set_source, only: [:show, :edit, :update]

  def index
    @sources = Source.all
  end

  def new
    @source = Source.new
  end

  def create
    @source = Source.new(source_params)
    if @source.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @source.update(source_params)
      redirect_to source_path(@source.id)
    else
      render :edit
    end
  end

  def destroy
    source = Source.find(params[:id])
    source.destroy
    redirect_to root_path
  end

  def search
    # @sources = Source.search(params[:keyword])
    @results = @p.result
    # .includes(:category_id_eq)
  end

  private
  def source_params
    params.require(:source).permit(:title, :category_id, :grade_id, :content).merge(admin_id: current_admin.id)
  end

  def set_source
    @source = Source.find(params[:id])
  end

  def move_to_index
    unless admin_signed_in?
      redirect_to root_path
    end
  end

  def search_source
    @p = Source.ransack(params[:q])
  end
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/sources/_search_form.html.erb
<h3>検索ボックスから記事を検索できます</h3>
<%= search_form_for search, url: search_sources_path, class: "search-box" do |f| %>
  <div class="search-form-innerbox">
    <%# <%= form.text_field :keyword, placeholder: "検索", class: "search-input" %>
    <%# <%= form.submit "検索", class: "search-btn" %> 
    <div class="form-parts">
      <%= f.label :title_cont, 'タイトル', class: "label" %><br>
      <%= f.search_field :title_cont, placeholder: 'キーワードを入力してください', class: "input-text" %>
    </div>

    <div class="form-parts">
      <%= f.label :category_id_eq, 'カテゴリー', class: "label" %><br>
      <%= f.collection_select :category_id_eq, Category.all, :id, :name, include_blank: '指定なし', class: "input-slelct" %>
    </div>

    <div class="form-parts">
      <%= f.label :grade_id_eq, '校種', class: "label" %><br>
      <%= f.collection_select :grade_id_eq, Grade.all, :id, :name, include_blank: '指定なし', class: "input-slelct" %>
    </div>

    <div class="form-parts">
      <%= f.label :content_cont, '概要', class: "label" %><br>
      <%= f.search_field :content_cont, placeholder: 'キーワードを入力してください', class: "input-text" %>
    </div>

    <div class="search-action">
      <%= f.submit '検索', id: "search-btn" %>
    </div>
  </div>
<% end %>

app/views/sources/_source.html.erb
<div class="source">
  <div class="source-upper">
    <%= link_to source.title, source_path(source.id) %>
  </div>
  <div class="source-bottom">
    <div class="source-bottom-left">
      カテゴリー：<%= source.category.name %>
    </div>
    <div class="source-bottom-right">
      校種：<%= source.grade.name %>
    </div>
  </div>
</div>

app/views/sources/edit.html.erb
<div class="contents-wrapper">
  <div class="contents">
    <div class="form-wrapper">
      <h1 class="source-action-title">編集</h1>
      <%= form_with(model: @source, local: true, class: "input-box") do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <div class="input-form-innerbox">
          <div class="form-parts">
            <%= f.label 'タイトル' %><br>
            <%= f.text_field :title, placeholder: 'タイトル', class: "input-text" %>
          </div>

          <div class="form-parts">
            <%= f.label 'カテゴリー', class: "label" %><br>
            <%= f.collection_select :category_id, Category.all, :id, :name, {include_blank: "---"}, class: "input-select" %>
          </div>

          <div class="form-parts">
            <%= f.label '校種', class: "label" %><br>
            <%= f.collection_select :grade_id, Grade.all, :id, :name, {include_blank: "---"}, class: "input-select" %>
          </div>

          <div class="form-parts">
            <%= f.label '概要', class: "label" %><br>
            <%= f.text_area :content, rows: "20", placeholder: '概要を入力してください', class: "input-text" %>
          </div>

          <div class="source-action">
            <%= f.submit "更新", id: "source-action-btn" %>
          </div>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/sources/index.html.erb
<%= render partial: "search_form", locals: { search: @p } %>
<% if admin_signed_in? %>
  <div class="sources">
    <% @sources.each do |source| %>
      <%= render partial: "source", locals: { source: source } %>
    <% end %>
  </div>
<% elsif user_signed_in? %>
<% else %>
  上のボタンからログインおよび新規登録してください
<% end %>

app/views/sources/new.html.erb
<div class="contents-wrapper">
  <div class="contents">
    <div class="form-wrapper">
      <h1 class="source-action-title">新規作成</h1>
      <%= form_with(model: @source, local: true, class: "input-box") do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <div class="input-form-innerbox">
          <div class="form-parts">
            <%= f.label 'タイトル' %><br>
            <%= f.text_field :title, placeholder: 'タイトル', class: "input-text" %>
          </div>

          <div class="form-parts">
            <%= f.label 'カテゴリー', class: "label" %><br>
            <%= f.collection_select :category_id, Category.all, :id, :name, {include_blank: "---"}, class: "input-select" %>
          </div>

          <div class="form-parts">
            <%= f.label '校種', class: "label" %><br>
            <%= f.collection_select :grade_id, Grade.all, :id, :name, {include_blank: "---"}, class: "input-select" %>
          </div>

          <div class="form-parts">
            <%= f.label '概要', class: "label" %><br>
            <%= f.text_area :content, rows: "20", placeholder: '概要を入力してください', class: "input-text" %>
          </div>

          <div class="source-action">
            <%= f.submit "作成", id: "source-action-btn" %>
          </div>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/sources/search.html.erb
<%= render partial: "search_form", locals: { search: @p } %>
<div class="contents row">
  <div class="sources">
    <span id="search-results">検索結果</span>
    <% if @results.length != 0 %>
      <% @results.each do |result| %>
        <%= render partial: "source", locals: { source: result } %>
      <% end %>
    <% else %>
      見つかりませんでした
    <% end %>
  </div>
</div>

app/views/sources/show.html.erb
<div class="contents-wrapper">
  <div class="contents">
    <% if admin_signed_in? %>
      <div class="edit-and-destroy-buttons">
        <%= link_to '編集', edit_source_path(@source.id), class: "edit-btn" %>
        <%= link_to '削除', source_path(@source.id), method: :delete, class: "del-btn", data: {confirm: "投稿を削除します。\nよろしいですか？"} %>
      </div>
    <% end %>
    <table class="source-table">
      <tr>
        <th class="single-row-table">タイトル</th>
        <td class="single-row-table"><%= @source.title %></td>
      </tr>

      <tr>
        <th class="single-row-table">カテゴリー</th>
        <td class="single-row-table"><%= @source.category.name %></tr>
      </tr>

      <tr>
        <th class="single-row-table">校種</th>
        <td class="single-row-table"><%= @source.grade.name %></tr>
      </tr>

      <tr>
        <th class="single-row-table">概要</th>
        <td><%= @source.content %></td>
      </tr>

    </table>
  </div>
</div>