config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  resources :admins
  resources :users
  resources :sources do
    collection do
      get 'search'
    end
  end
  root to: 'sources#index'
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>特別支援教育データベース</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', src: "https://code.jquery.com/jquery-3.3.1.min.js", integrity: "sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=", crossorigin: "anonymous" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header-left">
        <%= link_to '特別支援教育データベース', root_path %>
      </div>
      <div class="header-right">
        <% if admin_signed_in? %>
          <ul class="header-buttons">
            <li class="new-sources">
              <%= link_to '新規投稿', new_source_path, class: "new-source-button" %>
            </li>
            <li class="admin-session">
              <p class="menu-trigger">管理人</p>
            </li>
          </ul>
          <ul class="menu">
            <li class="menu-list" id="admin-edit">
              <%= link_to '管理者情報編集', edit_admin_registration_path %>
            </li>
            <li class="menu-list">
              <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %>
            </li>
          </ul>
        <% elsif user_signed_in? %>
          <ul class="header-buttons">
            <li class="new-sources">
              <%= link_to '新規投稿', new_source_path %>
            </li>
            <li class="user-session">
              <p class="menu-trigger"><%= current_user.name %></p>
            </li>
          </ul>
          <ul class="menu">
            <li class="menu-list" id="user-edit">
              <%= link_to 'ユーザー情報編集', edit_user_registration_path %>
            </li>
            <li class="menu-list">
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        <% else %>
          <%= link_to 'ログイン(Admin)', new_admin_session_path %>
          <%= link_to '新規登録(Admin)', new_admin_registration_path %>
          <%= link_to 'ログイン(User)', new_user_session_path %>
          <%= link_to '新規登録(User)', new_user_registration_path %>
        <% end %>
      </div>
    </header>
    <div class="contents-wrapper">
      <div class="contents">
        <%= yield %>
      </div>
    </div>
  </body>
</html>